import {CountryCode} from '@/constants/country-code';

export const countryCodeToTitle: Record<CountryCode, string> = {
	[CountryCode.AD]: 'Andorra',
	[CountryCode.AE]: 'دولة الإمارات العربية المتحدة',
	[CountryCode.AF]: 'افغانستان',
	[CountryCode.AG]: 'Antigua and Barbuda',
	[CountryCode.AI]: 'Anguilla',
	[CountryCode.AL]: 'Shqipëria',
	[CountryCode.AM]: 'Հայաստան',
	[CountryCode.AO]: 'Angola',
	[CountryCode.AR]: 'Argentina',
	[CountryCode.AS]: 'American Samoa',
	[CountryCode.AT]: 'Österreich',
	[CountryCode.AU]: 'Australia',
	[CountryCode.AW]: 'Aruba',
	[CountryCode.AZ]: 'Azərbaycan',
	[CountryCode.BA]: 'Bosna i Hercegovina',
	[CountryCode.BB]: 'Barbados',
	[CountryCode.BD]: 'Bangladesh',
	[CountryCode.BE]: 'België',
	[CountryCode.BF]: 'Burkina Faso',
	[CountryCode.BG]: 'България',
	[CountryCode.BH]: '‏البحرين',
	[CountryCode.BI]: 'Burundi',
	[CountryCode.BJ]: 'Bénin',
	[CountryCode.BL]: 'Saint-Barthélemy',
	[CountryCode.BM]: 'Bermuda',
	[CountryCode.BN]: 'Negara Brunei Darussalam',
	[CountryCode.BO]: 'Bolivia',
	[CountryCode.BQ]: 'Bonaire',
	[CountryCode.BR]: 'Brasil',
	[CountryCode.BS]: 'Bahamas',
	[CountryCode.BT]: 'ʼbrug-yul',
	[CountryCode.BV]: 'Bouvetøya',
	[CountryCode.BW]: 'Botswana',
	[CountryCode.BY]: 'Белару́сь',
	[CountryCode.BZ]: 'Belize',
	[CountryCode.CA]: 'Canada',
	[CountryCode.CC]: 'Cocos (Keeling) Islands',
	[CountryCode.CD]: 'République démocratique du Congo',
	[CountryCode.CF]: 'Ködörösêse tî Bêafrîka',
	[CountryCode.CG]: 'République du Congo',
	[CountryCode.CH]: 'Schweiz',
	[CountryCode.CI]: 'Côte d\'Ivoire',
	[CountryCode.CK]: 'Cook Islands',
	[CountryCode.CL]: 'Chile',
	[CountryCode.CM]: 'Cameroon',
	[CountryCode.CN]: '中国',
	[CountryCode.CO]: 'Colombia',
	[CountryCode.CR]: 'Costa Rica',
	[CountryCode.CU]: 'Cuba',
	[CountryCode.CV]: 'Cabo Verde',
	[CountryCode.CW]: 'Curaçao',
	[CountryCode.CX]: 'Christmas Island',
	[CountryCode.CY]: 'Κύπρος',
	[CountryCode.CZ]: 'Česká republika',
	[CountryCode.DE]: 'Deutschland',
	[CountryCode.DJ]: 'Djibouti',
	[CountryCode.DK]: 'Danmark',
	[CountryCode.DM]: 'Dominica',
	[CountryCode.DO]: 'República Dominicana',
	[CountryCode.DZ]: 'الجزائر',
	[CountryCode.EC]: 'Ecuador',
	[CountryCode.EE]: 'Eesti',
	[CountryCode.EG]: 'مصر‎',
	[CountryCode.EH]: 'الصحراء الغربية',
	[CountryCode.ER]: 'ኤርትራ',
	[CountryCode.ES]: 'España',
	[CountryCode.ET]: 'ኢትዮጵያ',
	[CountryCode.FI]: 'Suomi',
	[CountryCode.FJ]: 'Fiji',
	[CountryCode.FK]: 'Falkland Islands',
	[CountryCode.FM]: 'Micronesia',
	[CountryCode.FO]: 'Føroyar',
	[CountryCode.FR]: 'France',
	[CountryCode.GA]: 'Gabon',
	[CountryCode.GB]: 'United Kingdom',
	[CountryCode.GD]: 'Grenada',
	[CountryCode.GE]: 'საქართველო',
	[CountryCode.GF]: 'Guyane française',
	[CountryCode.GG]: 'Guernsey',
	[CountryCode.GH]: 'Ghana',
	[CountryCode.GI]: 'Gibraltar',
	[CountryCode.GL]: 'Kalaallit Nunaat',
	[CountryCode.GM]: 'Gambia',
	[CountryCode.GN]: 'Guinée',
	[CountryCode.GP]: 'Guadeloupe',
	[CountryCode.GQ]: 'Guinea Ecuatorial',
	[CountryCode.GR]: 'Ελλάδα',
	[CountryCode.GT]: 'Guatemala',
	[CountryCode.GU]: 'Guam',
	[CountryCode.GW]: 'Guiné-Bissau',
	[CountryCode.GY]: 'Guyana',
	[CountryCode.HK]: '香港',
	[CountryCode.HN]: 'Honduras',
	[CountryCode.HR]: 'Hrvatska',
	[CountryCode.HT]: 'Haïti',
	[CountryCode.HU]: 'Magyarország',
	[CountryCode.ID]: 'Indonesia',
	[CountryCode.IE]: 'Éire',
	[CountryCode.IL]: 'יִשְׂרָאֵל',
	[CountryCode.IM]: 'Isle of Man',
	[CountryCode.IN]: 'भारत',
	[CountryCode.IO]: 'British Indian Ocean Territory',
	[CountryCode.IQ]: 'العراق',
	[CountryCode.IR]: 'ایران',
	[CountryCode.IS]: 'Ísland',
	[CountryCode.IT]: 'Italia',
	[CountryCode.JE]: 'Jersey',
	[CountryCode.JM]: 'Jamaica',
	[CountryCode.JO]: 'الأردن',
	[CountryCode.JP]: '日本',
	[CountryCode.KE]: 'Kenya',
	[CountryCode.KG]: 'Кыргызстан',
	[CountryCode.KH]: 'Kâmpŭchéa',
	[CountryCode.KI]: 'Kiribati',
	[CountryCode.KM]: 'Komori',
	[CountryCode.KN]: 'Saint Kitts and Nevis',
	[CountryCode.KP]: '북한',
	[CountryCode.KR]: '대한민국',
	[CountryCode.KW]: 'الكويت',
	[CountryCode.KY]: 'Cayman Islands',
	[CountryCode.KZ]: 'Қазақстан',
	[CountryCode.LA]: 'ສປປລາວ',
	[CountryCode.LB]: 'لبنان',
	[CountryCode.LC]: 'Saint Lucia',
	[CountryCode.LI]: 'Liechtenstein',
	[CountryCode.LK]: 'śrī laṃkāva',
	[CountryCode.LR]: 'Liberia',
	[CountryCode.LS]: 'Lesotho',
	[CountryCode.LT]: 'Lietuva',
	[CountryCode.LU]: 'Luxembourg',
	[CountryCode.LV]: 'Latvija',
	[CountryCode.LY]: '‏ليبيا',
	[CountryCode.MA]: 'المغرب',
	[CountryCode.MC]: 'Monaco',
	[CountryCode.MD]: 'Moldova',
	[CountryCode.ME]: 'Црна Гора',
	[CountryCode.MF]: 'Saint-Martin',
	[CountryCode.MG]: 'Madagasikara',
	[CountryCode.MH]: 'M̧ajeļ',
	[CountryCode.MK]: 'Северна Македонија',
	[CountryCode.ML]: 'Mali',
	[CountryCode.MM]: 'မြန်မာ',
	[CountryCode.MN]: 'Монгол улс',
	[CountryCode.MO]: '澳門',
	[CountryCode.MP]: 'Northern Mariana Islands',
	[CountryCode.MQ]: 'Martinique',
	[CountryCode.MR]: 'موريتانيا',
	[CountryCode.MS]: 'Montserrat',
	[CountryCode.MT]: 'Malta',
	[CountryCode.MU]: 'Maurice',
	[CountryCode.MV]: 'Maldives',
	[CountryCode.MW]: 'Malawi',
	[CountryCode.MX]: 'México',
	[CountryCode.MY]: 'Malaysia',
	[CountryCode.MZ]: 'Moçambique',
	[CountryCode.NA]: 'Namibia',
	[CountryCode.NE]: 'Niger',
	[CountryCode.NF]: 'Norfolk Island',
	[CountryCode.NG]: 'Nigeria',
	[CountryCode.NI]: 'Nicaragua',
	[CountryCode.NL]: 'Nederland',
	[CountryCode.NO]: 'Norge',
	[CountryCode.NP]: 'नपल',
	[CountryCode.NR]: 'Nauru',
	[CountryCode.NU]: 'Niuē',
	[CountryCode.NZ]: 'New Zealand',
	[CountryCode.OM]: 'عمان',
	[CountryCode.PA]: 'Panamá',
	[CountryCode.PE]: 'Perú',
	[CountryCode.PF]: 'Polynésie française',
	[CountryCode.PG]: 'Papua Niugini',
	[CountryCode.PH]: 'Pilipinas',
	[CountryCode.PK]: 'Pakistan',
	[CountryCode.PL]: 'Polska',
	[CountryCode.PM]: 'Saint-Pierre-et-Miquelon',
	[CountryCode.PN]: 'Pitcairn Islands',
	[CountryCode.PR]: 'Puerto Rico',
	[CountryCode.PS]: 'فلسطين',
	[CountryCode.PT]: 'Portugal',
	[CountryCode.PW]: 'Palau',
	[CountryCode.PY]: 'Paraguay',
	[CountryCode.QA]: 'قطر',
	[CountryCode.RE]: 'La Réunion',
	[CountryCode.RO]: 'România',
	[CountryCode.RS]: 'Србија',
	[CountryCode.RU]: 'Россия',
	[CountryCode.RW]: 'Rwanda',
	[CountryCode.SA]: 'العربية السعودية',
	[CountryCode.SB]: 'Solomon Islands',
	[CountryCode.SC]: 'Seychelles',
	[CountryCode.SD]: 'السودان',
	[CountryCode.SE]: 'Sverige',
	[CountryCode.SG]: 'Singapore',
	[CountryCode.SH]: 'Saint Helena',
	[CountryCode.SI]: 'Slovenija',
	[CountryCode.SJ]: 'Svalbard og Jan Mayen',
	[CountryCode.SK]: 'Slovensko',
	[CountryCode.SL]: 'Sierra Leone',
	[CountryCode.SM]: 'San Marino',
	[CountryCode.SN]: 'Sénégal',
	[CountryCode.SO]: 'Soomaaliya',
	[CountryCode.SR]: 'Suriname',
	[CountryCode.SS]: 'South Sudan',
	[CountryCode.ST]: 'São Tomé e Príncipe',
	[CountryCode.SV]: 'El Salvador',
	[CountryCode.SX]: 'Sint Maarten',
	[CountryCode.SY]: 'سوريا',
	[CountryCode.SZ]: 'Swaziland',
	[CountryCode.TA]: 'Tristan da Cunha',
	[CountryCode.TC]: 'Turks and Caicos Islands',
	[CountryCode.TD]: 'Tchad',
	[CountryCode.TG]: 'Togo',
	[CountryCode.TH]: 'ประเทศไทย',
	[CountryCode.TJ]: 'Тоҷикистон',
	[CountryCode.TK]: 'Tokelau',
	[CountryCode.TL]: 'Timor-Leste',
	[CountryCode.TM]: 'Türkmenistan',
	[CountryCode.TN]: 'تونس',
	[CountryCode.TO]: 'Tonga',
	[CountryCode.TR]: 'Türkiye',
	[CountryCode.TT]: 'Trinidad and Tobago',
	[CountryCode.TV]: 'Tuvalu',
	[CountryCode.TW]: '臺灣',
	[CountryCode.TZ]: 'Tanzania',
	[CountryCode.UA]: 'Україна',
	[CountryCode.UG]: 'Uganda',
	[CountryCode.UM]: 'United States Minor Outlying Islands',
	[CountryCode.US]: 'United States',
	[CountryCode.UY]: 'Uruguay',
	[CountryCode.UZ]: 'O‘zbekiston',
	[CountryCode.VA]: 'Vaticano',
	[CountryCode.VC]: 'Saint Vincent and the Grenadines',
	[CountryCode.VE]: 'Venezuela',
	[CountryCode.VG]: 'British Virgin Islands',
	[CountryCode.VI]: 'United States Virgin Islands',
	[CountryCode.VN]: 'Việt Nam',
	[CountryCode.VU]: 'Vanuatu',
	[CountryCode.WF]: 'Wallis et Futuna',
	[CountryCode.WS]: 'Samoa',
	[CountryCode.XK]: 'Kosovë',
	[CountryCode.YE]: 'اليَمَن',
	[CountryCode.YT]: 'Mayotte',
	[CountryCode.ZA]: 'South Africa',
	[CountryCode.ZM]: 'Zambia',
	[CountryCode.ZW]: 'Zimbabwe',
};
